/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tarea01_JCMC_2025;

import javax.swing.JOptionPane;
import NuevoArticulo.Nuevo_Articulo;

import java.util.Date;
import javax.swing.ButtonModel;

/**
 *
 * @author José Carlos Manjón Carrasco
 */
public class Formulario extends javax.swing.JDialog {

    /**
     * Creates new form Formulario
     */
    public Formulario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGarantia = new javax.swing.ButtonGroup();
        jLabelCategoria = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelPrecioUnitario = new javax.swing.JLabel();
        jLabelStock = new javax.swing.JLabel();
        jLabelGarantia = new javax.swing.JLabel();
        jLabelEstadoArticulo = new javax.swing.JLabel();
        jLabelCompatibilidad = new javax.swing.JLabel();
        jLabelDescripcionDetallada = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcionDetallada = new javax.swing.JTextArea();
        jRadioButton12Meses = new javax.swing.JRadioButton();
        jRadioButton24Meses = new javax.swing.JRadioButton();
        jRadioButtonSinGarantia = new javax.swing.JRadioButton();
        jCheckBoxNuevo = new javax.swing.JCheckBox();
        jCheckBoxReacondicionado = new javax.swing.JCheckBox();
        jCheckBoxOfertaEspecial = new javax.swing.JCheckBox();
        jCheckBoxCompaWindows = new javax.swing.JCheckBox();
        jCheckBoxCompaUbuntu = new javax.swing.JCheckBox();
        jTextFieldPrecioUnitario = new javax.swing.JTextField();
        jTextFieldStockDisponible = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jLabelCodigoArticulo = new javax.swing.JLabel();
        jLabelNombreArticulo = new javax.swing.JLabel();
        jTextFieldCodigoArticulo = new javax.swing.JTextField();
        jTextFieldNombreArticulo = new javax.swing.JTextField();
        jTextFieldProveedor = new javax.swing.JTextField();
        jLabelFechaEntrada = new javax.swing.JLabel();
        jLabelProveedor = new javax.swing.JLabel();
        jSpinnerFechaEntrada = new javax.swing.JSpinner();
        jLabelTituloSeccion = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox();
        jCheckBoxCompaDebian = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelCategoria.setText("Categoría");

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setToolTipText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("Cancelar y borrar datos");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelPrecioUnitario.setText("Precio unitario");

        jLabelStock.setText("Stock disponible");

        jLabelGarantia.setText("Garantía");

        jLabelEstadoArticulo.setText("Estado del artículo");

        jLabelCompatibilidad.setText("Compatibilidad");

        jLabelDescripcionDetallada.setText("Descripción detallada");

        jTextAreaDescripcionDetallada.setColumns(20);
        jTextAreaDescripcionDetallada.setRows(5);
        jTextAreaDescripcionDetallada.setToolTipText("Descripción detallada");
        jScrollPane1.setViewportView(jTextAreaDescripcionDetallada);

        buttonGroupGarantia.add(jRadioButton12Meses);
        jRadioButton12Meses.setText("12 meses");
        jRadioButton12Meses.setToolTipText("12 meses");

        buttonGroupGarantia.add(jRadioButton24Meses);
        jRadioButton24Meses.setText("24 meses");
        jRadioButton24Meses.setToolTipText("24 meses");

        buttonGroupGarantia.add(jRadioButtonSinGarantia);
        jRadioButtonSinGarantia.setText("Sin Garantía");
        jRadioButtonSinGarantia.setToolTipText("Sin garantía");

        jCheckBoxNuevo.setText("Nuevo");
        jCheckBoxNuevo.setToolTipText("Nuevo");

        jCheckBoxReacondicionado.setText("Reacondicionado");
        jCheckBoxReacondicionado.setToolTipText("Reacondicionado");

        jCheckBoxOfertaEspecial.setText("Oferta especial");
        jCheckBoxOfertaEspecial.setToolTipText("Oferta especial");

        jCheckBoxCompaWindows.setText("Windows");
        jCheckBoxCompaWindows.setToolTipText("Windows");

        jCheckBoxCompaUbuntu.setText("Ubuntu");
        jCheckBoxCompaUbuntu.setToolTipText("Ubuntu");

        jTextFieldPrecioUnitario.setToolTipText("Precio por unidad");
        jTextFieldPrecioUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioUnitarioKeyTyped(evt);
            }
        });

        jTextFieldStockDisponible.setToolTipText("Stock disponible");
        jTextFieldStockDisponible.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldStockDisponibleKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        label1.setText("Prueba");

        jLabelCodigoArticulo.setText("Código del artículo");

        jLabelNombreArticulo.setText("Nombre del artículo");

        jTextFieldCodigoArticulo.setToolTipText("Código del articulo");
        jTextFieldCodigoArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoArticuloKeyTyped(evt);
            }
        });

        jTextFieldNombreArticulo.setToolTipText("Nombre del artículo");
        jTextFieldNombreArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreArticuloKeyTyped(evt);
            }
        });

        jTextFieldProveedor.setToolTipText("Proveedor");
        jTextFieldProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldProveedorKeyTyped(evt);
            }
        });

        jLabelFechaEntrada.setText("Fecha de entrada");

        jLabelProveedor.setText("Proveedor");

        jSpinnerFechaEntrada.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFechaEntrada.setToolTipText("Fecha de entrada");

        jLabelTituloSeccion.setText("Código del artículo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCodigoArticulo)
                        .addGap(37, 37, 37)
                        .addComponent(jTextFieldCodigoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombreArticulo)
                            .addComponent(jLabelTituloSeccion))
                        .addGap(32, 32, 32)
                        .addComponent(jTextFieldNombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFechaEntrada)
                    .addComponent(jLabelProveedor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldProveedor)
                    .addComponent(jSpinnerFechaEntrada))
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloSeccion)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigoArticulo)
                    .addComponent(jTextFieldCodigoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaEntrada)
                    .addComponent(jSpinnerFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreArticulo)
                    .addComponent(jTextFieldNombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProveedor)
                    .addComponent(jTextFieldProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ordenador", "Portátil", "Monitor", "Impresora", "Accesorio", "Componente interno", "Otro" }));
        jComboBoxCategoria.setToolTipText("Categoría");

        jCheckBoxCompaDebian.setText("Debian");
        jCheckBoxCompaDebian.setToolTipText("Debian");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCompatibilidad)
                            .addComponent(jLabelEstadoArticulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(357, 357, 357)
                                .addComponent(jButtonGuardar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxNuevo)
                                    .addComponent(jCheckBoxCompaWindows))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxReacondicionado)
                                    .addComponent(jCheckBoxCompaUbuntu))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxOfertaEspecial)
                                    .addComponent(jCheckBoxCompaDebian))
                                .addGap(75, 75, 75)))
                        .addGap(41, 41, 41)
                        .addComponent(jButtonCancelar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDescripcionDetallada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCategoria)
                                .addGap(50, 50, 50)
                                .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(jLabelGarantia)
                                .addGap(51, 51, 51)
                                .addComponent(jRadioButton12Meses)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton24Meses)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonSinGarantia))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelPrecioUnitario)
                                        .addGap(64, 64, 64))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelStock)
                                        .addGap(68, 68, 68)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldPrecioUnitario, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(jTextFieldStockDisponible))))
                        .addContainerGap(34, Short.MAX_VALUE))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGarantia)
                    .addComponent(jRadioButton12Meses)
                    .addComponent(jRadioButton24Meses)
                    .addComponent(jRadioButtonSinGarantia)
                    .addComponent(jLabelCategoria)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabelCompatibilidad)
                        .addGap(33, 33, 33)
                        .addComponent(jLabelDescripcionDetallada)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGuardar)
                            .addComponent(jButtonCancelar))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrecioUnitario)
                            .addComponent(jTextFieldPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStockDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStock))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEstadoArticulo)
                            .addComponent(jCheckBoxNuevo)
                            .addComponent(jCheckBoxReacondicionado)
                            .addComponent(jCheckBoxOfertaEspecial))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxCompaWindows)
                            .addComponent(jCheckBoxCompaUbuntu)
                            .addComponent(jCheckBoxCompaDebian))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
                null,
                "¿Desea salir sin guardar?",
                "Confirmación de salida",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {

            setVisible(false); // cerramos modal

        } else {
            jTextFieldCodigoArticulo.setText("");
            //  aquí se cierra formulario 

        }

    }//GEN-LAST:event_jButtonCancelarActionPerformed
    private boolean validarFormulario() {
        String codigoArt = jTextFieldCodigoArticulo.getText();
        String proveedor = jTextFieldProveedor.getText();
        String precioUnitari = jTextFieldPrecioUnitario.getText();
        if (codigoArt == null || "".equals(codigoArt)) {
            JOptionPane.showMessageDialog(this, "El campo Código de articulo no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (proveedor == null || "".equals(proveedor)) {
            JOptionPane.showMessageDialog(this, "El campo Proveedor no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (precioUnitari == null || "".equals(precioUnitari)) {
            JOptionPane.showMessageDialog(this, "El campo Precio unitario no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        try {
            Integer.parseInt(jTextFieldStockDisponible.getText());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "El campo Stock disponible debe ser un número entero", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;//si todo correcto
    }

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        float precioUnitario = Float.parseFloat(jTextFieldPrecioUnitario.getText());
        int stockD = Integer.parseInt(jTextFieldStockDisponible.getText());
        Date fecha = (Date) jSpinnerFechaEntrada.getValue();
        java.sql.Date fechaConstructor = new java.sql.Date(fecha.getTime());
        // Construcción del estado del artículo
        StringBuilder estadoArticulo = new StringBuilder();
        if (jCheckBoxNuevo.isSelected()) {
            estadoArticulo.append(jCheckBoxNuevo.getText()).append(", ");
        }
        if (jCheckBoxReacondicionado.isSelected()) {
            estadoArticulo.append(jCheckBoxReacondicionado.getText()).append(", ");
        }
        if (jCheckBoxOfertaEspecial.isSelected()) {
            estadoArticulo.append(jCheckBoxOfertaEspecial.getText()).append(", ");
        }
        // Eliminar la coma final si existe
        String estadoFinal = estadoArticulo.toString().trim().replaceAll(",\\s*$", "");
// Validar que al menos uno esté seleccionado
        if (estadoFinal.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Se debe seleccionar al menos un estado del artículo.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE
            );
        }

        StringBuilder compatiArticulo = new StringBuilder();
        if (jCheckBoxCompaWindows.isSelected()) {
            compatiArticulo.append(jCheckBoxCompaWindows.getText()).append(", ");
        }
        if (jCheckBoxCompaUbuntu.isSelected()) {
            compatiArticulo.append(jCheckBoxCompaUbuntu.getText()).append(", ");
        }
        if (jCheckBoxCompaDebian.isSelected()) {
            compatiArticulo.append(jCheckBoxCompaDebian.getText()).append(", ");
        }
        // Eliminar la coma final si existe
        String compatiArticuloFinal = compatiArticulo.toString().trim().replaceAll(",\\s*$", "");
// Validar que al menos uno esté seleccionado
        if (compatiArticuloFinal.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Se debe seleccionar al menos una compatibilidad.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE
            );
        }
        String garantiaSeleccionada = "";
        jRadioButton12Meses.setActionCommand("12 meses");
        jRadioButton24Meses.setActionCommand("24 meses");
        jRadioButtonSinGarantia.setActionCommand("sin garantía");
        try {
            ButtonModel garantiaArticulo = buttonGroupGarantia.getSelection();
            if (garantiaArticulo != null) {
                garantiaSeleccionada = garantiaArticulo.getActionCommand();
//                System.out.println("Seleccionado: " + garantiaSeleccionada.trim());
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Debes seleccionar una opción de garantía.",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE
                );
            }
        } catch (java.lang.NullPointerException e) {
            e.getMessage();
        }

        Nuevo_Articulo articuloEjemplo = new Nuevo_Articulo(
                jTextFieldCodigoArticulo.getText(), // códigoArticulo
                jTextFieldNombreArticulo.getText(),
                (String) jComboBoxCategoria.getSelectedItem(), // categoría
                precioUnitario, // precioUnitario
                stockD, // stockDisponible
                jTextFieldProveedor.getText(),//proveedor
                fechaConstructor,// fechaEntrada
                garantiaSeleccionada, // garantía en meses
                estadoFinal, // estadoArticulo
                compatiArticuloFinal, // compatibilidad
                jTextAreaDescripcionDetallada.getText()
        );
        System.out.println(articuloEjemplo.toString());

        if (validarFormulario()) {
            JOptionPane.showMessageDialog(this, "Formulario correcto");
            dispose();// no válido, ya que cierra la ventana diréctamente sin hacer limpiado
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextFieldStockDisponibleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStockDisponibleKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
// Muestra mensaje de advertencia
            JOptionPane.showMessageDialog(this,
                    "Solo se permiten números enteros en el campo de stock.",
                    "Entrada inválida",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jTextFieldStockDisponibleKeyTyped

    private void jTextFieldCodigoArticuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoArticuloKeyTyped
        // Verifica si ya hay 10 caracteres
        if (jTextFieldCodigoArticulo.getText().length() >= 10) {
            evt.consume();
            JOptionPane.showMessageDialog(this,
                    "El código de artículo no puede tener más de 10 dígitos.",
                    "Límite alcanzado",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldCodigoArticuloKeyTyped

    private void jTextFieldNombreArticuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreArticuloKeyTyped
        if (jTextFieldCodigoArticulo.getText().length() >= 50) {
            evt.consume();
            JOptionPane.showMessageDialog(this,
                    "El nombre de artículo no puede tener más de 50 dígitos.",
                    "Límite alcanzado",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldNombreArticuloKeyTyped

    private void jTextFieldProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProveedorKeyTyped
        if (jTextFieldCodigoArticulo.getText().length() >= 30) {
            evt.consume();
            JOptionPane.showMessageDialog(this,
                    "El proveedor no puede tener más de 30 dígitos.",
                    "Límite alcanzado",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldProveedorKeyTyped

    private void jTextFieldPrecioUnitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioUnitarioKeyTyped
        //la coma/ punto del decimal este código hace no pueda usarse
        char c = evt.getKeyChar();
        // if (!Character.isDigit(c) && c != '.' && c != ',') {
        if (!Character.isDigit(c)) {
            evt.consume();
// Muestra mensaje de advertencia
            JOptionPane.showMessageDialog(this,
                    "Solo se permiten números con dos decimlaes en el campo de Precio unitario.",
                    "Entrada inválida",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldPrecioUnitarioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Formulario dialog = new Formulario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroupGarantia;
    public javax.swing.JButton jButtonCancelar;
    public javax.swing.JButton jButtonGuardar;
    public javax.swing.JCheckBox jCheckBoxCompaDebian;
    public javax.swing.JCheckBox jCheckBoxCompaUbuntu;
    public javax.swing.JCheckBox jCheckBoxCompaWindows;
    public javax.swing.JCheckBox jCheckBoxNuevo;
    public javax.swing.JCheckBox jCheckBoxOfertaEspecial;
    public javax.swing.JCheckBox jCheckBoxReacondicionado;
    public javax.swing.JComboBox jComboBoxCategoria;
    public javax.swing.JLabel jLabelCategoria;
    public javax.swing.JLabel jLabelCodigoArticulo;
    public javax.swing.JLabel jLabelCompatibilidad;
    public javax.swing.JLabel jLabelDescripcionDetallada;
    public javax.swing.JLabel jLabelEstadoArticulo;
    public javax.swing.JLabel jLabelFechaEntrada;
    public javax.swing.JLabel jLabelGarantia;
    public javax.swing.JLabel jLabelNombreArticulo;
    public javax.swing.JLabel jLabelPrecioUnitario;
    public javax.swing.JLabel jLabelProveedor;
    public javax.swing.JLabel jLabelStock;
    public javax.swing.JLabel jLabelTituloSeccion;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JRadioButton jRadioButton12Meses;
    public javax.swing.JRadioButton jRadioButton24Meses;
    public javax.swing.JRadioButton jRadioButtonSinGarantia;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSpinner jSpinnerFechaEntrada;
    public javax.swing.JTextArea jTextAreaDescripcionDetallada;
    public javax.swing.JTextField jTextFieldCodigoArticulo;
    public javax.swing.JTextField jTextFieldNombreArticulo;
    public javax.swing.JTextField jTextFieldPrecioUnitario;
    public javax.swing.JTextField jTextFieldProveedor;
    public javax.swing.JTextField jTextFieldStockDisponible;
    public java.awt.Label label1;
    // End of variables declaration//GEN-END:variables

}
