/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tarea01_JCMC_2025;

import javax.swing.JOptionPane;
import NuevoArticulo.Nuevo_Articulo;
import java.util.Date;

/**
 *
 * @author José Carlos Manjón Carrasco
 */
public class Formulario extends javax.swing.JDialog {

    float precioUnitario = 0;
    int stockD = 0;
    Date fecha;

    /**
     * Creates new form Formulario
     */
    public Formulario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // jButtonSalir.addActionListener(new SalirActionListener());
        jButtonGuardar.addActionListener(new ValidacionesActionListener(jTextFieldCodigoArticulo, jLabelCodigoArticulo.getText()));
        jButtonGuardar.addActionListener(new ValidacionesActionListener(jTextFieldNombreArticulo, jLabelNombreArticulo.getText()));
        jButtonGuardar.addActionListener(new ValidacionesActionListener(jTextFieldProveedor, jLabelProveedor.getText()));
        jButtonGuardar.addActionListener(new ValidacionesActionListener(jTextFieldPrecioUnitario, jLabelPrecioUnitario.getText()));
        jButtonGuardar.addActionListener(new ValidacionesActionListener(jTextFieldStockDisponible, jLabelStock.getText()));
        jButtonGuardar.addActionListener(new ValidacionesGroupButton(buttonGroupGarantia));
//        jButtonGuardar.addActionListener(new ValidacionesActionListener(jTextAreaDescripcionDetallada, jLabelDescripcionDetallada.getText()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGarantia = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jLabelCodigoArticulo = new javax.swing.JLabel();
        jLabelNombreArticulo = new javax.swing.JLabel();
        jTextFieldCodigoArticulo = new javax.swing.JTextField();
        jTextFieldNombreArticulo = new javax.swing.JTextField();
        jTextFieldProveedor = new javax.swing.JTextField();
        jLabelFechaEntrada = new javax.swing.JLabel();
        jLabelProveedor = new javax.swing.JLabel();
        jSpinnerFechaEntrada = new javax.swing.JSpinner();
        jLabelTituloSeccion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxCategoria = new javax.swing.JComboBox();
        jLabelGarantia = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        jRadioButton12Meses = new javax.swing.JRadioButton();
        jRadioButton24Meses = new javax.swing.JRadioButton();
        jRadioButtonSinGarantia = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelPrecioUnitario = new javax.swing.JLabel();
        jTextFieldPrecioUnitario = new javax.swing.JTextField();
        jTextFieldStockDisponible = new javax.swing.JTextField();
        jLabelStock = new javax.swing.JLabel();
        jLabelEstadoArticulo = new javax.swing.JLabel();
        jCheckBoxNuevo = new javax.swing.JCheckBox();
        jCheckBoxReacondicionado = new javax.swing.JCheckBox();
        jCheckBoxOfertaEspecial = new javax.swing.JCheckBox();
        jLabelCompatibilidad = new javax.swing.JLabel();
        jCheckBoxCompaWindows = new javax.swing.JCheckBox();
        jCheckBoxCompaUbuntu = new javax.swing.JCheckBox();
        jCheckBoxCompaDebian = new javax.swing.JCheckBox();
        jLabelDescripcionDetallada = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcionDetallada = new javax.swing.JTextArea();
        jButtonGuardar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label1.setText("Prueba");

        jLabelCodigoArticulo.setText("Código del artículo");

        jLabelNombreArticulo.setText("Nombre del artículo");

        jTextFieldCodigoArticulo.setToolTipText("Código del articulo");
        jTextFieldCodigoArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoArticuloKeyTyped(evt);
            }
        });

        jTextFieldNombreArticulo.setToolTipText("Nombre del artículo");
        jTextFieldNombreArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreArticuloKeyTyped(evt);
            }
        });

        jTextFieldProveedor.setToolTipText("Proveedor");
        jTextFieldProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldProveedorKeyTyped(evt);
            }
        });

        jLabelFechaEntrada.setText("Fecha de entrada");

        jLabelProveedor.setText("Proveedor");

        jSpinnerFechaEntrada.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFechaEntrada.setToolTipText("Fecha de entrada");

        jLabelTituloSeccion.setText("Formulario ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelCodigoArticulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldCodigoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelTituloSeccion)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelNombreArticulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jTextFieldNombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabelFechaEntrada))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabelProveedor)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldProveedor)
                    .addComponent(jSpinnerFechaEntrada))
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloSeccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigoArticulo)
                    .addComponent(jTextFieldCodigoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaEntrada)
                    .addComponent(jSpinnerFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreArticulo)
                    .addComponent(jTextFieldNombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProveedor)
                    .addComponent(jTextFieldProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ordenador", "Portátil", "Monitor", "Impresora", "Accesorio", "Componente interno", "Otro" }));
        jComboBoxCategoria.setToolTipText("Categoría");

        jLabelGarantia.setText("Garantía");

        jLabelCategoria.setText("Categoría");

        buttonGroupGarantia.add(jRadioButton12Meses);
        jRadioButton12Meses.setText("12 meses");
        jRadioButton12Meses.setToolTipText("12 meses");

        buttonGroupGarantia.add(jRadioButton24Meses);
        jRadioButton24Meses.setText("24 meses");
        jRadioButton24Meses.setToolTipText("24 meses");

        buttonGroupGarantia.add(jRadioButtonSinGarantia);
        jRadioButtonSinGarantia.setText("Sin Garantía");
        jRadioButtonSinGarantia.setToolTipText("Sin garantía");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCategoria)
                .addGap(75, 75, 75)
                .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabelGarantia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jRadioButton12Meses)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton24Meses)
                .addGap(27, 27, 27)
                .addComponent(jRadioButtonSinGarantia)
                .addGap(118, 118, 118))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGarantia)
                    .addComponent(jLabelCategoria)
                    .addComponent(jRadioButton24Meses)
                    .addComponent(jRadioButtonSinGarantia)
                    .addComponent(jRadioButton12Meses))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLabelPrecioUnitario.setText("Precio unitario");

        jTextFieldPrecioUnitario.setToolTipText("Precio por unidad, máximo 10000 €");
        jTextFieldPrecioUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioUnitarioKeyTyped(evt);
            }
        });

        jTextFieldStockDisponible.setToolTipText("Stock disponible");
        jTextFieldStockDisponible.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldStockDisponibleKeyTyped(evt);
            }
        });

        jLabelStock.setText("Stock disponible");

        jLabelEstadoArticulo.setText("Estado del artículo");

        jCheckBoxNuevo.setText("Nuevo");
        jCheckBoxNuevo.setToolTipText("Nuevo");

        jCheckBoxReacondicionado.setText("Reacondicionado");
        jCheckBoxReacondicionado.setToolTipText("Reacondicionado");

        jCheckBoxOfertaEspecial.setText("Oferta especial");
        jCheckBoxOfertaEspecial.setToolTipText("Oferta especial");

        jLabelCompatibilidad.setText("Compatibilidad");

        jCheckBoxCompaWindows.setText("Windows");
        jCheckBoxCompaWindows.setToolTipText("Windows");

        jCheckBoxCompaUbuntu.setText("Ubuntu");
        jCheckBoxCompaUbuntu.setToolTipText("Ubuntu");

        jCheckBoxCompaDebian.setText("Debian");
        jCheckBoxCompaDebian.setToolTipText("Debian");

        jLabelDescripcionDetallada.setText("Descripción detallada");

        jTextAreaDescripcionDetallada.setColumns(20);
        jTextAreaDescripcionDetallada.setRows(5);
        jTextAreaDescripcionDetallada.setToolTipText("Descripción detallada");
        jScrollPane1.setViewportView(jTextAreaDescripcionDetallada);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPrecioUnitario)
                    .addComponent(jLabelStock)
                    .addComponent(jLabelDescripcionDetallada))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPrecioUnitario, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jTextFieldStockDisponible))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCompatibilidad)
                            .addComponent(jLabelEstadoArticulo))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxCompaWindows)
                            .addComponent(jCheckBoxNuevo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxReacondicionado)
                            .addComponent(jCheckBoxCompaUbuntu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxCompaDebian)
                            .addComponent(jCheckBoxOfertaEspecial))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrecioUnitario)
                    .addComponent(jLabelEstadoArticulo)
                    .addComponent(jCheckBoxNuevo)
                    .addComponent(jCheckBoxReacondicionado)
                    .addComponent(jCheckBoxOfertaEspecial))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStockDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStock)
                    .addComponent(jLabelCompatibilidad)
                    .addComponent(jCheckBoxCompaWindows)
                    .addComponent(jCheckBoxCompaUbuntu)
                    .addComponent(jCheckBoxCompaDebian))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescripcionDetallada)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131))
        );

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setToolTipText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGuardar)
                .addGap(35, 35, 35)
                .addComponent(jButtonSalir)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalir)
                    .addComponent(jButtonGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean validarFormulario() {
//        String codigoArt = jTextFieldCodigoArticulo.getText();
//        String proveedor = jTextFieldProveedor.getText();
//        String precioUnitari = jTextFieldPrecioUnitario.getText();
//        if (codigoArt == null || "".equals(codigoArt)) {
//            JOptionPane.showMessageDialog(this, "El campo Código de articulo no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
//            return false;
//        }
//        if (proveedor == null || "".equals(proveedor)) {
//            JOptionPane.showMessageDialog(this, "El campo Proveedor no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
//            return false;
//        }
//        if (precioUnitari == null || "".equals(precioUnitari)) {
//            JOptionPane.showMessageDialog(this, "El campo Precio unitario no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
//            return false;
//        }
        try {
            Integer.parseInt(jTextFieldStockDisponible.getText());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "El campo Stock disponible debe ser un número entero", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        try {
            precioUnitario = Float.parseFloat(jTextFieldPrecioUnitario.getText().trim().replace(',', '.'));
            stockD = Integer.parseInt(jTextFieldStockDisponible.getText());
        } catch (java.lang.NumberFormatException e) {
            e.getMessage();
            return false;
        }

        return true;//si todo correcto
    }

//    public static boolean esCampoValido(String texto, String nombreCampo) {
//        if (texto == null || texto.trim().isEmpty()) {
//            JOptionPane.showMessageDialog(null,
//                    "El campo '" + nombreCampo + "' no puede estar vacío.",
//                    "Validación de campos",
//                    JOptionPane.WARNING_MESSAGE
//            );
//            return false;
//        }
//        return true;
//    }

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed

        fecha = (Date) jSpinnerFechaEntrada.getValue();
        java.sql.Date fechaConstructor = new java.sql.Date(fecha.getTime());
        // Construcción del estado del artículo
        StringBuilder estadoArticulo = new StringBuilder();
        if (jCheckBoxNuevo.isSelected()) {
            estadoArticulo.append(jCheckBoxNuevo.getText()).append(", ");
        }
        if (jCheckBoxReacondicionado.isSelected()) {
            estadoArticulo.append(jCheckBoxReacondicionado.getText()).append(", ");
        }
        if (jCheckBoxOfertaEspecial.isSelected()) {
            estadoArticulo.append(jCheckBoxOfertaEspecial.getText()).append(", ");
        }
        // Eliminar la coma final si existe
        String estadoFinal = estadoArticulo.toString().trim().replaceAll(",", "");
// Validar que al menos uno esté seleccionado
        if (estadoFinal.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Se debe seleccionar al menos un estado del artículo.",
                    "Validación de campos",
                    JOptionPane.WARNING_MESSAGE
            );
        }

        StringBuilder compatiArticulo = new StringBuilder();
        if (jCheckBoxCompaWindows.isSelected()) {
            compatiArticulo.append(jCheckBoxCompaWindows.getText()).append(", ");
        }
        if (jCheckBoxCompaUbuntu.isSelected()) {
            compatiArticulo.append(jCheckBoxCompaUbuntu.getText()).append(", ");
        }
        if (jCheckBoxCompaDebian.isSelected()) {
            compatiArticulo.append(jCheckBoxCompaDebian.getText()).append(", ");
        }
        // Eliminar la coma final si existe
        String compatiArticuloFinal = compatiArticulo.toString().trim().replaceAll(",\\s*$", "");
// Validar que al menos uno esté seleccionado
        if (compatiArticuloFinal.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Se debe seleccionar al menos una compatibilidad.",
                    "Validación de campos",
                    JOptionPane.WARNING_MESSAGE
            );
        }
        String garantiaSeleccionada = "";
//        jRadioButton12Meses.setActionCommand("12 meses");
//        jRadioButton24Meses.setActionCommand("24 meses");
//        jRadioButtonSinGarantia.setActionCommand("sin garantía");
//        try {
//            ButtonModel garantiaArticulo = buttonGroupGarantia.getSelection();
//            if (garantiaArticulo != null) {
//                garantiaSeleccionada = garantiaArticulo.getActionCommand();
////                System.out.println("Seleccionado: " + garantiaSeleccionada.trim());
//            } else {
//                JOptionPane.showMessageDialog(
//                        this,
//                        "Debes seleccionar una opción de garantía.",
//                        "Advertencia",
//                        JOptionPane.WARNING_MESSAGE
//                );
//            }
//        } catch (java.lang.NullPointerException e) {
//            e.getMessage();
//        }

        Nuevo_Articulo articuloEjemplo = new Nuevo_Articulo(
                jTextFieldCodigoArticulo.getText(), // códigoArticulo
                jTextFieldNombreArticulo.getText(),
                (String) jComboBoxCategoria.getSelectedItem(), // categoría
                precioUnitario, // precioUnitario
                stockD, // stockDisponible
                jTextFieldProveedor.getText(),//proveedor
                fechaConstructor,// fechaEntrada
                garantiaSeleccionada, // garantía en meses
                estadoFinal, // estadoArticulo
                compatiArticuloFinal, // compatibilidad
                jTextAreaDescripcionDetallada.getText()
        );
        System.out.println(articuloEjemplo.toString());

        if (validarFormulario()) {
            JOptionPane.showMessageDialog(this, "Formulario correcto");
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextFieldStockDisponibleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStockDisponibleKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
// Muestra mensaje de advertencia
            JOptionPane.showMessageDialog(this,
                    "Solo se permiten números enteros en el campo de stock.",
                    "Entrada inválida",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jTextFieldStockDisponibleKeyTyped

    private void jTextFieldCodigoArticuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoArticuloKeyTyped
        // Verifica si ya hay 10 caracteres
        if (jTextFieldCodigoArticulo.getText().length() >= 10) {
            evt.consume();
            JOptionPane.showMessageDialog(this,
                    "El código de artículo no puede tener más de 10 dígitos.",
                    "Límite alcanzado",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldCodigoArticuloKeyTyped

    private void jTextFieldNombreArticuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreArticuloKeyTyped
        if (jTextFieldCodigoArticulo.getText().length() >= 50) {
            evt.consume();
            JOptionPane.showMessageDialog(this,
                    "El nombre de artículo no puede tener más de 50 dígitos.",
                    "Límite alcanzado",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldNombreArticuloKeyTyped

    private void jTextFieldProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProveedorKeyTyped
        if (jTextFieldCodigoArticulo.getText().length() >= 30) {
            evt.consume();
            JOptionPane.showMessageDialog(this,
                    "El proveedor no puede tener más de 30 dígitos.",
                    "Límite alcanzado",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldProveedorKeyTyped

    private void jTextFieldPrecioUnitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioUnitarioKeyTyped

        char c = evt.getKeyChar();

        // Permitir dígitos, punto y coma como separadores decimales
        boolean esValido = Character.isDigit(c) || c == '.' || c == ',';
        int VALORMAXIMO = 10000;

        if (!esValido) {
            evt.consume();
            JOptionPane.showMessageDialog(this,
                    "Solo se permiten números con punto o coma decimal.",
                    "Entrada inválida",
                    JOptionPane.WARNING_MESSAGE
            );
        }
        try {

            float valor = Float.parseFloat(jTextFieldPrecioUnitario.getText());
            if (valor > VALORMAXIMO) {
                evt.consume();
                JOptionPane.showMessageDialog(this,
                        "El precio unitario no puede superar los 10000€.",
                        "Validación de campos",
                        JOptionPane.WARNING_MESSAGE
                );
            }
        } catch (NumberFormatException ex) {
            ex.getMessage();// No mostrar error aquí, ya que el número aún puede estar incompleto
        }


    }//GEN-LAST:event_jTextFieldPrecioUnitarioKeyTyped

    private void jButtonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseClicked
        int opcion = JOptionPane.showConfirmDialog(
                null,
                "¿Desea salir sin guardar?",
                "Confirmación de salida",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {

            setVisible(false); // cerramos modal

        } else {

            //  aquí se cierra formulario 
        }

    }//GEN-LAST:event_jButtonSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Formulario dialog = new Formulario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroupGarantia;
    public javax.swing.JButton jButtonGuardar;
    public javax.swing.JButton jButtonSalir;
    public javax.swing.JCheckBox jCheckBoxCompaDebian;
    public javax.swing.JCheckBox jCheckBoxCompaUbuntu;
    public javax.swing.JCheckBox jCheckBoxCompaWindows;
    public javax.swing.JCheckBox jCheckBoxNuevo;
    public javax.swing.JCheckBox jCheckBoxOfertaEspecial;
    public javax.swing.JCheckBox jCheckBoxReacondicionado;
    public javax.swing.JComboBox jComboBoxCategoria;
    public javax.swing.JLabel jLabelCategoria;
    public javax.swing.JLabel jLabelCodigoArticulo;
    public javax.swing.JLabel jLabelCompatibilidad;
    public javax.swing.JLabel jLabelDescripcionDetallada;
    public javax.swing.JLabel jLabelEstadoArticulo;
    public javax.swing.JLabel jLabelFechaEntrada;
    public javax.swing.JLabel jLabelGarantia;
    public javax.swing.JLabel jLabelNombreArticulo;
    public javax.swing.JLabel jLabelPrecioUnitario;
    public javax.swing.JLabel jLabelProveedor;
    public javax.swing.JLabel jLabelStock;
    public javax.swing.JLabel jLabelTituloSeccion;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JRadioButton jRadioButton12Meses;
    public javax.swing.JRadioButton jRadioButton24Meses;
    public javax.swing.JRadioButton jRadioButtonSinGarantia;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSpinner jSpinnerFechaEntrada;
    public javax.swing.JTextArea jTextAreaDescripcionDetallada;
    public javax.swing.JTextField jTextFieldCodigoArticulo;
    public javax.swing.JTextField jTextFieldNombreArticulo;
    public javax.swing.JTextField jTextFieldPrecioUnitario;
    public javax.swing.JTextField jTextFieldProveedor;
    public javax.swing.JTextField jTextFieldStockDisponible;
    public java.awt.Label label1;
    // End of variables declaration//GEN-END:variables

}
